version: '3.9'
services:
  front_end:
    restart: always
    build: ./front_end
    container_name: front_end
    environment:
      - VIRTUAL_HOST=test.polybond.dev
      - VIRUTAL_PORT=81
      - VIRTUAL_PATH=/
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=polybond.dev
      - LETSENCRYPT_EMAIL=amelnychukoseen@polybond.dev
    expose:
      - "8000"
    ports:
      - 81:80

networks:
  default:
    name: hydra_frontend
    external: true
