version: '3.9'
services:
  nginx:
    container_name: nginx
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - docker_vol:ro
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/nginx/certs:/etc/nginx/certs
      - /var/docker/nginx/vhost:/etc/nginx/vhost.d
      - /etc/nginx/conf.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt-companion:
    container_name: letsencrypt-companion
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    volumes_from:
      - nginx
    volumes:
      - docker_vol
      - /var/docker/nginx/acme:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: amelnychukoseen@polybond.dev

  hello-world:
    container_name: hello-world
    image: kornkitti/express-hello-world
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=polybond.dev
      - VIRTUAL_PATH=/helloworld
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=polybond.dev
      - LETSENCRYPT_EMAIL=amelnychukoseen@polybond.dev


networks:
  default:
    name: hydra_frontend

volumes:
  docker_vol:
    name: docker_vol
      - /var/run/docker.sock:/var/run/docker.sock

  

