version: '3.9'
services:
  hello-world:
    restart: always
    container_name: hello-world
    image: kornkitti/express-hello-world
    expose:
      - "8080"
    environment:
      - VIRTUAL_HOST=polybond.dev
      - VIRTUAL_PATH=/helloworld
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=polybond.dev
      - LETSENCRYPT_EMAIL=amelnychukoseen@polybond.dev
    networks:
      - frontend

networks:
  frontend:
    name: hydra_frontend
    external: true